### ISSUE TITLE
New features for cards and transfers

### ISSUE THREAD

**Issue by arner** [ben8p/home-assistant-bunq-balance-sensors#16]
Thanks for the helpful integration.

I made some updates in a fork that you might be interested in. The code is here: https://github.com/ben8p/home-assistant-bunq-balance-sensors/compare/master...arner:home-assistant-bunq-balance-sensors:cards_payments?expand=1 . Feedback would be appreciated! If you like the concept I can create a PR and we can discuss what's needed to make it ready to merge. 

# Cards

- You can see your credit- and debitcards as sensors. The state is the name of the currently connected account (if this account exists in home assistant). Attributes include the limit and atm limit.
- The service bunq.link_account takes a card sensor and an account sensor as input. It changes the primary connected account of that card to the selected account.

# Transfer to own account

The bunq.transfer service lets you transfer a specified amount of the base currency of the account to any of your own accounts that you imported to home assistant, with an optional message.

# Why?

You can:

- see your balances and connected cards on your dashboard at a glance
- organize your monthly budgets when your salary comes in
- select the right account for your debitcard based on being at work, in your car, or on specific times or whatever other data you have in home assistant
- reward yourself by automatically transferring some money from your savings to your fun account whenever you went for a run
- ...!

**Comment by ben8p** [comment]
Hi!
I love the idea! That's brilliant! Thank you very much for this!

I skimmed the code and it overall looks pretty solid.
I do have a few minor questions regarding the change. 

Let's make a PR and discuss them in the review.

**Comment by arner** [comment]
Nice, thanks for the quick review and merge.
