### ISSUE TITLE
HASS logs reports Direct I/O error

### ISSUE THREAD

**Issue by dgreebe** [ben8p/home-assistant-bunq-balance-sensors#3]
Logger: homeassistant.util.async_
Source: util/async_.py:120
First occurred: 8:49:32 PM (1456 occurrences)
Last logged: 9:38:36 PM

Detected I/O inside the event loop. This is causing stability issues. Please report issue to the custom component author for bunq doing I/O at custom_components/bunq/api.py, line 104: "X-Bunq-Client-Request-Id": _request_id,
Detected I/O inside the event loop. This is causing stability issues. Please report issue to the custom component author for bunq doing I/O at custom_components/bunq/api.py, line 141: "X-Bunq-Client-Authentication": installation_token,
Detected I/O inside the event loop. This is causing stability issues. Please report issue to the custom component author for bunq doing I/O at custom_components/bunq/api.py, line 159: "X-Bunq-Client-Authentication": installation_token,
Detected I/O inside the event loop. This is causing stability issues. Please report issue to the custom component author for bunq doing I/O at custom_components/bunq/api.py, line 183: "X-Bunq-Client-Authentication": _session_token,
Detected I/O inside the event loop. This is causing stability issues. Please report issue to the custom component author for bunq doing I/O at custom_components/bunq/api.py, line 216: "X-Bunq-Client-Authentication": _session_token,

Using this plugin indeed makes my instance rather slow.

**Comment by ben8p** [comment]
Thanks for reporting.
I will take a look at it ASAP

**Comment by ben8p** [comment]
@dgreebe the issue should be fixed. If you are using HACS you should be able to update soon.
