### ISSUE TITLE
Doesnt work

### ISSUE THREAD

**Issue by umutcelebi** [ben8p/home-assistant-bunq-balance-sensors#4]
I couldnt get this to work when following the steps? Everything is fine config but does not add any sensors. Is this still working?

**Comment by ben8p** [comment]
Hi,
Yes it still works. I am using it daily.

When you generate the api key, you need to add it to the configuration and restart Hass within 5 minutes if I remember correctly.

Also you may have to go back in the bunk app to approve the IP address (I don't remember if that's a necessary step)

**Comment by umutcelebi** [comment]
Hi, i tried this like you said but no difference unfortunately. The API is not called since Bunq app says nothing just stays same...

**Comment by ben8p** [comment]
Maybe the configuration is not in the right place.
The bunq sensor needs to be added in the sensor section of the configuration.yaml

My configuration is split like describe here : https://opensource.com/article/21/2/home-assistant-custom-sensors
The bunq sensor is in my sensor.yml file.

Can you check this too?

**Comment by umutcelebi** [comment]
Yes i have checked this.
I already have another hacs component added as a sensor and that one works. I implemented this one like that one so it should work i guess..

**Comment by ben8p** [comment]
Can you share your configuration (of course remember to hide the api key).

Did you check the logs?
Maybe there's something in there.

Also, that sounds obvious but just to double check: your Hass instance has access to the internet?

**Comment by umutcelebi** [comment]
This is my sensor yaml:
    - platform: afvalbeheer
      wastecollector: Cyclus
      resources:
        - restafval
        - gft
        - papier
        - pmd
      postcode: 
      streetnumber: 
      upcomingsensor: 0
      dateformat: '%d-%m-%Y'
      dutch: 1
    - platform: bunq
      api_key: "xxxxx4ab4c"
      permitted_ips: "mywanip"
There is internet to HA and i do not see any errors related to this custom component.

**Comment by ben8p** [comment]
Hmmm
I really have no clue what's going on...

Can you try to follow https://www.home-assistant.io/integrations/logger/ and enable debug logging for the component?

I'm not entirely sure what is the workspace so try to enable it for "bunq" and for "custom_components.bunq"

After restarting Hass there should be some debug log available in the supervisor.

If there's nothing, try to put the default logger to "debug" (but then brace yourself, there will be a lot of logs).

When you get logs, search for the bunq ones.
Hopefully there will be some stuff that will help us debug it.

**Comment by umutcelebi** [comment]
Error:
Logger: homeassistant.components.sensor
Source: custom_components/bunq/api.py:119
Integration: Sensor (documentation, issues)
First occurred: 23:42:56 (1 occurrences)
Last logged: 23:42:56

Error while setting up bunq platform for sensor
Traceback (most recent call last):
  File "/config/custom_components/bunq/api.py", line 100, in _setup_context
    async with session.post(
  File "/usr/local/lib/python3.9/site-packages/aiohttp/client.py", line 1117, in __aenter__
    self._resp = await self._coro
  File "/usr/local/lib/python3.9/site-packages/aiohttp/client.py", line 544, in _request
    await resp.start(conn)
  File "/usr/local/lib/python3.9/site-packages/aiohttp/client_reqrep.py", line 905, in start
    self._continue = None
  File "/usr/local/lib/python3.9/site-packages/aiohttp/helpers.py", line 656, in __exit__
    raise asyncio.TimeoutError from None
asyncio.exceptions.TimeoutError

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/entity_platform.py", line 250, in _async_setup_platform
    await asyncio.shield(task)
  File "/config/custom_components/bunq/sensor.py", line 44, in async_setup_platform
    active_accounts = await get_active_accounts(True)
  File "/config/custom_components/bunq/api.py", line 225, in get_active_accounts
    await _setup_context()
  File "/config/custom_components/bunq/api.py", line 119, in _setup_context
    installation,
UnboundLocalError: local variable 'installation' referenced before assignment

**Comment by ben8p** [comment]
Thanks, 
According to the log there is a timeout when the component try to reach `https://api.bunq.com`  
I have the feeling somehow the internet traffic is restricted on your instance.

**Comment by umutcelebi** [comment]
Issue with firewall or something you think? I need to check that one than...

**Comment by ben8p** [comment]
It might be indeed.
Let me know if you find something

**Comment by umutcelebi** [comment]
I have just switched from rpi3 to a celeron minipc. Now it is working fine. I am not sure what the difference is. First time putting the key and it was directly added to HA. Thanks anyway for the help. Just cant figure out what was issue before on rpi.

**Comment by ben8p** [comment]
That's interesting.
I am using it on a rpi3 as well.


If you still have the pi with hassio on it, you could try to install the ssh plugin then 
`ping api.bunq.com`.

It does not respond to ping, but at least you should see the IP address behind the url.

I am closing the issue for now, feel free to reopen if you have more to share.
