### ISSUE TITLE
Dynamic transaction view in lovelace

### ISSUE THREAD

**Issue by umutcelebi** [ben8p/home-assistant-bunq-balance-sensors#5]
Hi,

I have the transaction card and a mini graph card which works perfect but i was also curious if it is possible to make something Dyme does? (https://dyme.app/)
So when i tap that view in my lovelace i will have logos and the money they are send or received. Thanks!

**Comment by ben8p** [comment]
I am not sure you can mimic everything from dyme but in theory yes, you can do something similar.
However it is not trivial.
You will need to create a custom Lovelace card, and it will most likely involved a lot of JavaScript.
You can take a look at the data provided by bunq  and see if it has what you need.
https://doc.bunq.com/#/payment/List_all_Payment_for_User_MonetaryAccount

**Comment by umutcelebi** [comment]
Thank you verry much but this is much harder than i thought it would be. Do you only use the transaction card? Or can you give me other examples and tips about this?
