### ISSUE TITLE
Transaction Card is empty

### ISSUE THREAD

**Issue by Boogaard53** [ben8p/home-assistant-bunq-balance-sensors#6]
This is what the cards look like in my Lovelace view.
The sensor with the amount of money does work, but however, the transaction card is empty, although I do have made several payments.

![Overview - Home ](https://user-images.githubusercontent.com/87951112/132192742-c106a61d-6d67-4d23-9e7d-9b919de28d67.png)

**Comment by ben8p** [comment]
Did you install html-template-card as well?

**Comment by Boogaard53** [comment]
Yes i did, both the normal Lovelace Html Card
, and the HTML ninja2 template card

**Comment by ben8p** [comment]
hmmm, the bunq integration seems to work. Otherwise you would have no sensors.  
so I assume it is a problem with the template.

If you visit https://github.com/piotrmachowski/home-assistant-lovelace-html-jinja2-template-card and try the example card .

does it work ?

**Comment by Boogaard53** [comment]
No it says: 'No card type configured'. Altough I installed it twice both through hacs and manually

**Comment by ben8p** [comment]
Best would be to raise a bug there: https://github.com/PiotrMachowski/Home-Assistant-Lovelace-HTML-Jinja2-Template-card/issues

They will be able to give you better support on how to make the card work

**Comment by Boogaard53** [comment]
That card is working, but the bunq card is still empty/blankl. One of the people that helped me said this but I don't know what to do with the info he gave me:

"It means that your template is invalid (probably invalid entity id: sensor.bunq_groceries). You can paste this config in dev tools and it should work"

**Comment by ben8p** [comment]
Yes it's correct, you need to replace "sensor.bunq_groceries" by the name of your sensor

**Comment by Boogaard53** [comment]
Thank you! I did it, I thought that everyone would have the sensor with the same name (mine is sensor.bunq_geld).

**Comment by ben8p** [comment]
The name of the sensor is the name of the bank account (you can have multiple sensors if you use multiple accounts)

**Comment by Boogaard53** [comment]
One last thing, i have a savings account in my bunq app but it didn't show up as a sensor. Can I add it somehow?

**Comment by ben8p** [comment]
Hmmm
I would have to check the api provided by bunq, but I guess they are not considered a monetary account.

Current implementation only support monetary accounts

**Comment by ben8p** [comment]
Tested recently and I could see saving accounts. Can you confirm?

**Comment by Boogaard53** [comment]
Yup! i can see my savings

**Comment by ben8p** [comment]
Awesome!
Thanks for confirming
