### ISSUE TITLE
Sensor for shared account (en/of rekening) not showing.

### ISSUE THREAD

**Issue by iMartien** [ben8p/home-assistant-bunq-balance-sensors#7]
The plugin only shows my own account, not my shared (en/of) account. Do I need to do anything to show them? Or is this a bug or maybe nog possible?

**Comment by ben8p** [comment]
Hi,
That's correct. 

Currently the plugin only supports personal monetary accounts. Shared accounts and savings accounts are not supported.

**Comment by rhopman** [comment]
Hi @ben8p and @iMartien, I created PR #10 for this.

**Comment by ben8p** [comment]
Hi @iMartien @rhopman I merged the PR.

@rhopman Thanks for the contribution

**Comment by iMartien** [comment]
Pretty cool, thanks for the great work guys! @rhopman @ben8p
